### ISSUE TITLE
Versionskonflikt zwischen client und server: "subtitle" Attribut fehlt

### ISSUE THREAD

**Issue by versus-chris** [iabudiab/dependency-track-maven-plugin#10]
Maven-Log:
[ERROR] Failed to execute goal dev.iabudiab:dependency-track-maven-plugin:1.1.0:upload-bom (strict) on project XXXX: Error processing project findings: Unrecognized field "subtitle" (class iabudiab.maven.plugins.dependencytrack.client.model.Vulnerability), not marked as ignorable (11 known properties: "title", "severityRank", "uuid", "vulnId", "severity", "subTitle", "source", "cweId", "cweName", "description", "recommendation"])

**Comment by iabudiab** [comment]
This is strange, because the [Vulnerability](https://github.com/DependencyTrack/dependency-track/blob/8767a35149692a515d05c8916d29d3e6a723b6a9/src/main/java/org/dependencytrack/model/Vulnerability.java#L125) class on the server uses camel case.

A quick fix for now would be to let Jackson to ignore all unknown properties. A new bugfix release is in the works ;)

**Comment by iabudiab** [comment]
A workaround (JSON Ignore for unknown fields) is in v1.1.1
